### ISSUE TITLE
Could u please drop a link or a tutorial video on how to create a Google api tts auth key? That would be really helpful 

### ISSUE THREAD

**Issue by minnu03** [j3rk0/blind-mailAI#1]

**Comment by j3rk0** [comment]
Hi, Happy to see that our project has intrested you.
https://m.youtube.com/watch?v=y_vQvAqgqgA
This video should cover all the required step to get the api key.
If you're intrested in porting the project to other languages this can be easly done by editing the utils/generate_dataset.py and the utils/get_corpus.sh. The First generate a set of sentences that reproduce the tipical interactions the user could have with the systems (sentences and token classes must be specified) while the ladder Simply download a generic corpus in the system's language.

**Comment by minnu03** [comment]
Thank you!!! Also could u please tell the json format, what's the key value I'm supposed to assign the token to?

**Comment by j3rk0** [comment]
do you solved that problem ? i don't think i understood
