### ISSUE TITLE
ASR fine tuning step 1 "run fine tuning notebook. this will get you a models/wav2vec2 folder with torch model", couldnt find fine tuning notebook.

### ISSUE THREAD

**Issue by minnu03** [j3rk0/blind-mailAI#2]

**Comment by j3rk0** [comment]
it's the notebooks/asr/train_asr.py
i will change the readme to be more clear

**Comment by j3rk0** [comment]
done editinig the readme with the path of the python file to execute. Mind that when i talk about 'notebook' i'm not using jupyter but ipython that can be executed as a standard python script

**Comment by j3rk0** [comment]
If I can ask, your interest in this project is just academical, or you're actually building the system for someone??

**Comment by minnu03** [comment]
> done editinig the readme with the path of the python file to execute. Mind that when i talk about 'notebook' i'm not using jupyter but ipython that can be executed as a standard python script

thanksss!!

**Comment by minnu03** [comment]
> If I can ask, your interest in this project is just academical, or you're actually building the system for someone??

It's both actually. I really liked the idea of using lm and neural networks,, seems very unique. I wanted to try the implementation just so I could learn and understand the capabilities of the app.  Thank you for your contribution.
